#!/usr/bin/env bash
# .verify.sh — L0 ground-truth gate (auto-generated by gen-verify-gate.sh).
# Runs the repo's real checks in order, stops on first failure, prints the
# actual exit code. Regenerate with: ~/.hermes/scripts/gen-verify-gate.sh
#
# HONESTY CONTRACT: this gate only runs checks that exist. It does NOT invent
# a test suite. If a repo has no runnable checks it exits 1 on purpose so a
# missing gate can never look like a passing one.
set -uo pipefail
cd "$(dirname "$0")"

FAILED=0
run_step() {  # run_step <label> <cmd...>
  local label="$1"; shift
  echo "── $label ──"
  if "$@"; then
    echo "   ✓ $label"
  else
    rc=$?
    echo "   ✗ $label (exit $rc)"
    FAILED=1
    return $rc
  fi
}

# Python tool runner: prefer the repo's .venv, then .venv-lancedb, then PATH.
# PYTHONPATH/VIRTUAL_ENV are unset so the Hermes runtime's site-packages can't
# shadow the repo venv (this pollution bit the fleet index before).
run_py_tool() {  # run_py_tool <tool> <args...>
  local tool="$1"; shift
  if [ -x ".venv/bin/$tool" ]; then env -u PYTHONPATH -u VIRTUAL_ENV ".venv/bin/$tool" "$@"; return $?; fi
  if [ -x ".venv-lancedb/bin/$tool" ]; then env -u PYTHONPATH -u VIRTUAL_ENV ".venv-lancedb/bin/$tool" "$@"; return $?; fi
  if command -v "$tool" >/dev/null 2>&1; then env -u PYTHONPATH -u VIRTUAL_ENV "$tool" "$@"; return $?; fi
  echo "   (tool '$tool' not found — install it or point .venv at it)"
  return 127
}

run_step "npm run test" npm run test
run_step "npm run build" npm run build

if [ "$FAILED" -eq 0 ]; then
  echo "verify: PASS"
  exit 0
else
  echo "verify: FAIL"
  exit 1
fi
